# Generated by Django 2.2.1 on 2019-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
