# Generated by Django 2.2.1 on 2019-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0002_auto_20191216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='show_number',
            field=models.IntegerField(),
        ),
    ]
